name: Playwright Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    # Trigger on all pull requests regardless of target branch
  workflow_dispatch:

jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '18'
        cache: 'npm'
        cache-dependency-path: |
          src/web/package-lock.json
          tests/package-lock.json

    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.0.x'

    - name: Restore .NET dependencies
      run: dotnet restore
      working-directory: ./src/api

    - name: Build .NET API
      run: dotnet build --no-restore
      working-directory: ./src/api

    - name: Install frontend dependencies
      run: npm ci
      working-directory: ./src/web

    - name: Build frontend
      run: npm run build
      working-directory: ./src/web

    - name: Install test dependencies
      run: npm ci
      working-directory: ./tests

    - name: Install Playwright Browsers
      run: npx playwright install --with-deps
      working-directory: ./tests

    - name: Start API server
      run: |
        dotnet run --no-build &
        echo "API_PID=$!" >> $GITHUB_ENV
        # Wait for API to be ready (check Swagger endpoint)
        timeout 60 bash -c 'until curl -f http://localhost:3100 2>/dev/null || curl -f http://localhost:3100/lists 2>/dev/null; do sleep 2; done'
      working-directory: ./src/api
      env:
        ASPNETCORE_ENVIRONMENT: Development
        ASPNETCORE_URLS: http://localhost:3100

    - name: Start frontend server
      run: |
        npm run preview -- --port 3000 --host &
        echo "WEB_PID=$!" >> $GITHUB_ENV
        # Wait for frontend to be ready
        timeout 60 bash -c 'until curl -f http://localhost:3000 2>/dev/null; do sleep 2; done'
      working-directory: ./src/web
      env:
        VITE_API_BASE_URL: http://localhost:3100

    - name: Run Playwright tests
      run: npx playwright test
      working-directory: ./tests
      env:
        REACT_APP_WEB_BASE_URL: http://localhost:3000
        CI: true

    - name: Upload Playwright Report
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: tests/playwright-report/
        retention-days: 30

    - name: Upload Test Results
      uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: test-results
        path: tests/test-results/
        retention-days: 30

    - name: Cleanup processes
      if: always()
      run: |
        if [ ! -z "$API_PID" ]; then
          kill $API_PID || true
        fi
        if [ ! -z "$WEB_PID" ]; then
          kill $WEB_PID || true
        fi
